
# Add your actual RapidAPI key below
RAPIDAPI_KEY = "your_actual_rapidapi_key_here"

# Yahoo Fantasy API credentials
YAHOO_CONSUMER_KEY = "dj0yJmk9V0FGMzNaZUNVckNIJmQ9WVdrOU1XRjJOazF2Vm0wbWNHbzlNQT09JnM9Y29uc3VtZXJzZWNyZXQmc3Y9MCZ4PTRk"
YAHOO_CONSUMER_SECRET = "9d43ec9caa17a1b36671014dac8253728f1a0fe0"
